koiban/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('movie.urls')),
    # path('admin/', admin.site.urls),
]

movie/urls.py
from django.urls import path, re_path

from . import views

app_name = 'movie'
urlpatterns = [
    # ex. /, /film
    path('', views.FilmListView.as_view(), name='index'),
    path('film/', views.FilmListView.as_view(), name='film_list'),

    # ex. /film/1000000
    path('film/<int:pk>/', views.FilmDetailView.as_view(), name='film_detail'),

    # ex. /actor/
    path('actor/', views.ActorListView.as_view(), name='actor_list'),

    # ex. /movie/actor/1000000
    path('actor/<int:pk>/', views.ActorDetailView.as_view(), name='actor_detail'),

    # ex. /search/film/doraemon
    # ex. /search/actor/doraemon
    # ex. /search/comment/good
    re_path(r'^search/(?P<category>film|actor|comment)/(?P<search_term>[^/]+)/', views.search, name='search')
]

movie/models.py
from django.db import models


# Create your models here.
class Film(models.Model):
    short_title = models.CharField(max_length=50)
    full_title = models.CharField(max_length=100, db_index=True)
    alt_titles = models.CharField("alternative titles", max_length=350, db_index=True)
    rating = models.CharField(max_length=4, default='0.0')
    cover_url = models.URLField("cover image url")
    directors = models.CharField(max_length=150)
    screenwriters = models.CharField(max_length=200)
    genre = models.CharField(max_length=40)
    official_site = models.URLField()
    prod_region = models.CharField(max_length=40)
    language = models.CharField(max_length=50)
    premiere_dates = models.CharField(max_length=80)
    length = models.CharField(max_length=120)
    imdb = models.SlugField(max_length=10, db_index=False)
    year = models.CharField(max_length=6)
    synopsis = models.TextField()


class Actor(models.Model):
    name = models.CharField(max_length=70, db_index=True)
    fullname = models.CharField(max_length=40, db_index=True)
    douban_url = models.URLField()
    films = models.ManyToManyField(Film)
    screen_partners = models.ManyToManyField('self', symmetrical=False)
    sex = models.CharField(max_length=1)
    horoscope = models.CharField(max_length=3)
    birth_date = models.CharField(max_length=10)
    birth_place = models.CharField(max_length=38)
    careers = models.CharField(max_length=30)
    other_names = models.CharField(max_length=300)
    alt_zh_names = models.CharField(max_length=100)
    family = models.CharField(max_length=200)
    imdb = models.SlugField(max_length=10, db_index=False)
    introduction = models.TextField()
    photo_url = models.URLField()
    website_url = models.URLField()

    def __str__(self):
        return self.name


class Comment(models.Model):
    username = models.CharField(max_length=15)
    submit_time = models.CharField(max_length=10)
    text = models.TextField(db_index=True)
    film = models.ForeignKey(Film, on_delete=models.CASCADE)

    def __str__(self):
        return self.text

movie/views.py
import time

from django.core.paginator import Paginator
from django.shortcuts import render
from django.http import HttpResponse
from django.views import generic
from django.db.models import Q

from .models import Film, Actor, Comment


# Create your views here.
class FilmListView(generic.ListView):
    model = Film
    context_object_name = 'films'
    paginate_by = 20

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context['total_count'] = Film.objects.count()
        return context

    def get_ordering(self):
        return ['-rating', '-premiere_dates']


class FilmDetailView(generic.DetailView):
    model = Film


class ActorListView(generic.ListView):
    model = Actor
    context_object_name = 'actors'
    paginate_by = 20

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context['total_count'] = Actor.objects.count()
        return context

    def get_queryset(self):
        return Actor.objects.exclude(photo_url__exact='').order_by('name')


class ActorDetailView(generic.DetailView):
    model = Actor

    def get_screen_partners(self):
        actor = self.get_object()

        class Partner:
            def __init__(self, partner_id, name, photo_url, count):
                self.partner_id = partner_id
                self.name = name
                self.photo_url = photo_url
                self.count = count

            def __str__(self):
                return str(self.count)

        partners = []
        for partner in actor.screen_partners.all():
            collaborations = actor.films.intersection(partner.films.all())
            partners.append(Partner(partner.id, partner.name, partner.photo_url, collaborations.count()))

        partners.sort(key=lambda x: x.count, reverse=True)
        return partners[:10]


def search(request, category, search_term):
    if category == 'film':
        search_model = Film.objects.all().prefetch_related("actor_set")
        search_filter = Q(full_title__icontains=search_term) \
                        | Q(actor__name__icontains=search_term)\
                        | Q(actor__fullname__icontains=search_term)
    elif category == 'actor':
        search_model = Actor.objects.all().prefetch_related("films")
        search_filter = Q(name__icontains=search_term) \
                        | Q(fullname__icontains=search_term) \
                        | Q(films__full_title=search_term)
    elif category == 'comment':
        search_model = Comment.objects.all().prefetch_related("film")
        search_filter = Q(text__icontains=search_term)

    start_time = time.time()
    search_results = search_model.filter(search_filter).distinct()
    count = search_results.count()  # force retrieval
    time_taken = "{:.3f}".format(time.time() - start_time)
    total = search_model.count()

    paginator = Paginator(search_results, 20)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'movie/{}_search_results.html'.format(category),
                  {'query': search_term,
                   'page_obj': page_obj,
                   'total_count': count,
                   'time_taken': time_taken,
                   'total': total,
                   'category': category})

movie/templates/movie/actor_detail.html
{% extends "movie/base.html" %}

{% block title %}{{ actor.name }}{% endblock %}

{% block actor-active %} active{% endblock %}

{% block actor-search %}selected="selected"{% endblock %}

{% block content %}
<div style="text-align: center;"><h1>{% if actor.fullname|length > 0 %}{{ actor.fullname }}{% else %}{{ actor.name }}{% endif %}</h1></div>
<div class="row">
    <div class="col-lg-3 d-flex">
        <div class="card card-body flex-fill">
            <img class="card-img" src="{{ actor.photo_url|default:'https://img9.doubanio.com/f/movie/8dd0c794499fe925ae2ae89ee30cd225750457b4/pics/movie/celebrity-default-medium.png' }}" alt="{{ actor.name }}照片">
        </div>
    </div>
    <div class="col-lg-9 d-flex">
        <div class="card card-body flex-fill">
            {% if actor.fullname|length == 0 %}<span>没有演员详细资料</span>{% endif %}
            {% if actor.sex|length > 0 %}<span>性别: {{ actor.sex }}</span>{% endif %}
            {% if actor.horoscope|length > 0 %}<span>星座: {{ actor.horoscope }}</span>{% endif %}
            {% if actor.birth_date|length > 0 %}<span>出生日期: {{ actor.birth_date }}</span>{% endif %}
            {% if actor.birth_place|length > 0 %}<span>出生地: {{ actor.birth_place }}</span>{% endif %}
            {% if actor.careers|length > 0 %}<span>职业: {{ actor.careers }}</span>{% endif %}
            {% if actor.other_names|length > 0 %}<span>更多外文名: {{ actor.other_names }}</span>{% endif %}
            {% if actor.alt_zh_names|length > 0 %}<span>更多中文名: {{ actor.alt_zh_names }}</span>{% endif %}
            {% if actor.family|length > 0 %}<span>家庭成员: {{ actor.family }}</span>{% endif %}
            {% if actor.imdb|length > 0 %}<span>IMDb编号: <a href="https://www.imdb.com/name/{{ actor.imdb }}">{{ actor.imdb }}</a></span>{% endif %}
            {% if actor.website_url|length > 0 %}<span>官方网站: <a href="{{ actor.website_url }}">{{ actor.website_url }}</a></span>{% endif %}
        </div>
    </div>
</div>
{% if actor.introduction|length > 0 %}
<div class="card mt-5">
<h3>影人简介</h3>
<p>{{ actor.introduction }}</p>
</div>
{% endif %}
<h3 class="mt-5">参演影视:</h3>
{% for film in actor.films.all %}
{% if forloop.first %}
<div class="row">
    <div class="card-group">
{% endif %}
        <div class="card">
            <a href="{% url 'movie:film_detail' film.id %}"><img class="card-img-top" src="{{ film.cover_url}}" alt="{{ film.short_title }} cover"></a>
            <div class="card-body">
                <a href="{% url 'movie:film_detail' film.id %}"><h6 class="card-title">{{ film.short_title|title }}</h6></a>
                <p class="card-text"><small class="text-muted">{{ film.rating }}</small></p>
            </div>
        </div>
    {% if forloop.counter|divisibleby:'6' %}
    </div>
    <div class="card-group">
    {% endif %}
{% if forloop.last %}
    </div>
</div>
{% endif %}
{% empty %}
<p>没有相关作品</p>
{% endfor %}
<h3 class="mt-5">合作演员:</h3>
{% for partner in view.get_screen_partners %}
{% if forloop.first %}
<div class="row">
    <div class="card-group">
{% endif %}
        <div class="card">
            <a href="{% url 'movie:actor_detail' partner.partner_id %}"><img class="card-img-top" src="{{ partner.photo_url|default:'https://img9.doubanio.com/f/movie/8dd0c794499fe925ae2ae89ee30cd225750457b4/pics/movie/celebrity-default-medium.png' }}" alt="{{ partner.name }} photo"></a>
            <div class="card-body">
                <a href="{% url 'movie:actor_detail' partner.partner_id %}"><h6 class="card-title">{{ partner.name }} ({{ partner.count }})</h6></a>
            </div>
        </div>
    {% if forloop.counter|divisibleby:'6' %}
    </div>
    <div class="card-group">
    {% endif %}
{% if forloop.last %}
    </div>
</div>
{% endif %}
{% empty %}
<p>没有合作演员信息</p>
{% endfor %}
{% endblock %}

movie/templates/movie/actor_list.html
{% extends "movie/base.html" %}

{% block title %}演员列表{% endblock %}

{% block actor-active %} active{% endblock %}

{% block actor-search %}selected="selected"{% endblock %}

{% block content %}
{% for actor in actors %}
{% if forloop.first %}
<div class="row">
    <div class="card-group">
{% endif %}
        <div class="col">
            <div class="card">
                <a href="{% url 'movie:actor_detail' actor.id %}">
                    <img class="card-img-top" src="{{ actor.photo_url|default:'https://img9.doubanio.com/f/movie/8dd0c794499fe925ae2ae89ee30cd225750457b4/pics/movie/celebrity-default-medium.png' }}" alt="{{ actor.name }}照片">
                </a>
                <div class="card-body">
                    <a href="{% url 'movie:actor_detail' actor.id %}"><h6 class="card-title">{{ actor.name }}</h6></a>
                </div>
            </div>
        </div>
    {% if forloop.counter|divisibleby:'5' %}
    </div>
    <div class="card-group">
    {% endif %}
{% if forloop.last %}
    </div>
</div>
{% endif %}
{% empty %}
<p>没有演员信息</p>
{% endfor %}
{% endblock %}

movie/templates/movie/actor_search_results.html
{% extends "movie/base_search_results.html" %}

{% block category-zh %}演员{% endblock %}

{% block actor-search %}selected="selected"{% endblock %}

{% block content %}
{{ block.super }}
{% for actor in page_obj %}
{% if forloop.first %}
<div class="list-group">
{% endif %}
    <a href="{% url 'movie:actor_detail' actor.id %}" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="media">
            <img class="mr-3" src="{{ actor.photo_url|default:'https://img9.doubanio.com/f/movie/8dd0c794499fe925ae2ae89ee30cd225750457b4/pics/movie/celebrity-default-medium.png' }}" style="max-height: 96px">
            <div class="media-body">
                <h5 class="mt-0">{{ actor.name }}</h5>
            </div>
        </div>
    </a>
{% if forloop.last %}
</div>
{% endif %}
{% empty %}
    <p class="bg-warning">未找到匹配结果</p>
{% endfor %}
{% endblock %}

movie/templates/movie/base.html
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}KOIBan{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'movie/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'movie/fa/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'movie/layout.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'movie/favicon.ico' %}"/>
</head>
<body>

<nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'movie:index' %}">KOIBan</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-between" id="navbarNavAltMarkup">
    <div class="navbar-nav">
        <a class="nav-item nav-link{% block film-active %}{% endblock %}" href="{% url 'movie:film_list' %}">电影<span class="sr-only">(current)</span></a>
        <a class="nav-item nav-link{% block actor-active %}{% endblock %}" href="{% url 'movie:actor_list' %}">演员</a>
    </div>
        <form class="form-inline">
            <input class="form-control" type="search" placeholder="电影/演员/关键词" aria-label="Search" id="queryInput" value="{% block current_query %}{% endblock %}">
            <div class="input-group">
                <select class="form-control" id="searchCategory">
                    <option value="film" {% block film-search %}{% endblock %}>电影</option>
                    <option value="actor" {% block actor-search %}{% endblock %}>演员</option>
                    <option value="comment" {% block comment-search %}{% endblock %}>评论</option>
                </select>
                <button class="btn btn-outline-light" type="submit" onclick="search(); return false;">搜索</button>
            </div>
        </form>
    </div>
</nav>

<div class="container mt-2 mb-4">
    {% block content %}
        <p>Perfectly fine content</p>
    {% endblock %}
</div>

{% if page_obj.has_other_pages %}
    {% include 'movie/pagination.html' %}
{% endif %}

<script src="{% static 'movie/jquery/jquery.min.js' %}"></script>
<script src="{% static 'movie/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'movie/forms.js' %}"></script>
</body>
</html>

movie/templates/movie/base_search_results.html
{% extends "movie/base.html" %}

{% block title %}{{ query }} - {% block category-zh %}{% endblock %} - 搜索结果{% endblock %}

{% block current_query %}{{ query }}{% endblock %}

{% block content %}
    <small class="text-muted">相关结果共{{ total_count }}个，搜索条目共{{ total }}个，搜索花费时间是{{ time_taken }}秒</small>
{% endblock %}

movie/templates/movie/comment_search_results.html
{% extends "movie/base_search_results.html" %}

{% block category-zh %}演员{% endblock %}

{% block comment-search %}selected="selected"{% endblock %}

{% block content %}
{{ block.super }}
{% for comment in page_obj %}
{% if forloop.first %}
<div class="list-group">
{% endif %}
    <a href="{% url 'movie:film_detail' comment.film.id %}" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">{{ comment.username }}</h5>
            <small>{{ comment.film.short_title }}</small>
        </div>
        <p class="mb-1">{{ comment.text }}</p>
    </a>
{% if forloop.last %}
</div>
{% endif %}
{% empty %}
    <p class="bg-warning">未找到匹配结果</p>
{% endfor %}
{% endblock %}

movie/templates/movie/film_detail.html
{% extends "movie/base.html" %}

{% block title %}{{ film.full_title }}{% endblock %}

{% block film-active %} active{% endblock %}

{% block content %}
<div style="text-align: center;"><h1>{{ film.full_title }} {{ film.year }}</h1></div>
<div class="row">
    <div class="col-lg-3 d-flex">
        <div class="card card-body flex-fill">
            <img class="card-img" src="{{ film.cover_url}}" alt="{{ film.short_title }}海报">
        </div>
    </div>
    <div class="col-lg-9 d-flex">
        <div class="card card-body flex-fill">
            {% if film.directors|length > 0 %}<span>导演: {{ film.directors }}</span>{% endif %}
            {% if film.screenwriters|length > 0 %}<span>编剧: {{ film.screenwriters }}</span>{% endif %}
            {% if film.genre|length > 0 %}<span>类型: {{ film.genre }}</span>{% endif %}
            {% if film.official_site|length > 0 %}<span>官方网站: {{ film.official_site }}</span>{% endif %}
            {% if film.prod_region|length > 0 %}<span>制片国家/地区: {{ film.prod_region }}</span>{% endif %}
            {% if film.language|length > 0 %}<span>语言: {{ film.language }}</span>{% endif %}
            {% if film.premiere_dates|length > 0 %}<span>上映日期: {{ film.premiere_dates }}</span>{% endif %}
            {% if film.length|length > 0 %}<span>片长: {{ film.length }}</span>{% endif %}
            {% if film.alt_titles|length > 0 %}<span>又名: {{ film.alt_titles }}</span>{% endif %}
            {% if film.imdb|length > 0 %}<span>IMDb链接: <a href="https://www.imdb.com/title/{{ film.imdb }}">{{ film.imdb }}</a></span>{% endif %}
        </div>
    </div>
</div>
{% for actor in film.actor_set.all %}
{% if forloop.first %}
<h3 class="mt-4">主演:</h3>
<div class="row">
    <div class="card-group">
{% endif %}
        <div class="card">
            <a href="{% url 'movie:actor_detail' actor.id %}">
                <img class="card-img-top" src="{{ actor.photo_url|default:'https://img9.doubanio.com/f/movie/8dd0c794499fe925ae2ae89ee30cd225750457b4/pics/movie/celebrity-default-medium.png' }}" alt="{{ actor.name }}照片">
            </a>
            <div class="card-body">
                <a href="{% url 'movie:actor_detail' actor.id %}"><h6 class="card-title">{{ actor.name }}</h6></a>
            </div>
        </div>
    {% if forloop.counter|divisibleby:'6' %}
    </div>
    <div class="card-group">
    {% endif %}
{% if forloop.last %}
    </div>
</div>
{% endif %}
{% endfor %}
<h3 class="mt-4">影评:</h3>
{% for comment in film.comment_set.all %}
    {% if forloop.first %}
    <ul class="list-group list-group-flush">
    {% endif %}
        <li class="list-group-item"><i>{{ comment.username }}:<br></i> {{ comment.text }}</li>
    {% empty %}
    <p>没有任何影评</p>
    {% if forloop.last %}
    </ul>
    {% endif %}
{% endfor %}
{% endblock %}

movie/templates/movie/film_list.html
{% extends "movie/base.html" %}

{% block title %}电影列表{% endblock %}

{% block film-active %} active{% endblock %}

{% block content %}
{% for film in films %}
{% if forloop.first %}
<div class="row">
    <div class="card-group">
{% endif %}
        <div class="card">
            <a href="{% url 'movie:film_detail' film.id %}"><img class="card-img-top" src="{{ film.cover_url}}" alt="{{ film.short_title }}海报"></a>
            <div class="card-body">
                <a href="{% url 'movie:film_detail' film.id %}"><h6 class="card-title">{{ film.short_title|title }}</h6></a>
                <p class="card-text"><small class="text-muted">{{ film.rating }}</small></p>
            </div>
        </div>
    {% if forloop.counter|divisibleby:'5' %}
    </div>
    <div class="card-group">
    {% endif %}
{% if forloop.last %}
    </div>
</div>
{% endif %}
{% empty %}
<p>没有电影信息</p>
{% endfor %}
{% endblock %}

movie/templates/movie/film_search_results.html
{% extends "movie/base_search_results.html" %}

{% block category-zh %}电影{% endblock %}

{% block film-search %}selected="selected"{% endblock %}

{% block content %}
{{ block.super }}
{% for film in page_obj %}
{% if forloop.first %}
<div class="list-group">
{% endif %}
    <a href="{% url 'movie:film_detail' film.id %}" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="media">
            <img class="mr-3" src="{{ film.cover_url }}" alt="{{ film.short_title }}海报" style="max-height: 96px">
            <div class="media-body">
                <h5 class="mt-0">{{ film.short_title }}</h5>
                <small>{{ film.rating }}</small>
            </div>
        </div>
    </a>
{% if forloop.last %}
</div>
{% endif %}
{% empty %}
    <p class="bg-warning">未找到匹配结果</p>
{% endfor %}
{% endblock %}

movie/templates/movie/pagination.html
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
    {% if page_obj.number == 1 %}
        <li class="page-item disabled"><a class="page-link" href="#"><i class="fa fa-angle-double-left" aria-hidden="true"></i></a></li>
    {% else %}
        <li class="page-item"><a class="page-link" href="?page=1"><i class="fa fa-angle-double-left" aria-hidden="true"></i></a></li>
    {% endif %}

    {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="#"><i class="fa fa-angle-left" aria-hidden="true"></i></a></li>
    {% else %}
        <li class="page-item disabled"><a class="page-link" href="#"><i class="fa fa-angle-left" aria-hidden="true"></i></a></li>
    {% endif %}

    {% if page_obj.number|add:'-4' > 1 %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.number|add:'-5' }}">&hellip;</a></li>
    {% endif %}

    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
            <li class="page-item active"><a class="page-link" href="#">{{ i }}</a><span class="sr-only">(current)</span></li>
        {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
    {% endfor %}

    {% if page_obj.paginator.num_pages > page_obj.number|add:'4' %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.number|add:'5' }}">&hellip;</a></li>
    {% endif %}

    {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}"><i class="fa fa-angle-right" aria-hidden="true"></i></a></li>
    {% else %}
        <li class="page-item disabled"><a class="page-link" href="#"><i class="fa fa-angle-right" aria-hidden="true"></i></a></li>
    {% endif %}

    {% if page_obj.number == page_obj.paginator.num_pages %}
        <li class="page-item disabled"><a class="page-link" href="#"><i class="fas fa-angle-double-right" aria-hidden="true"></i></a></li>
    {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}"><i class="fa fa-angle-double-right" aria-hidden="true"></i></a></li>
    {% endif %}
        <li>
        <form class="form-inline" method="get">
            <input class="form-control ml-sm-2" type="number" placeholder="跳转至" aria-label="Jump" id="jump">
            <button class="btn btn-outline-success" type="submit" onclick="jumpToPage({{ page_obj.paginator.num_pages }}); return false;">跳转</button>
        </form>
        </li>
        <li class="page-item disabled"><a class="page-link ml-2" href="#">共{{ total_count }}条</a></li>
    </ul>
</nav>